server:
  port: 8081

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://119.45.140.92:3306/zero-one?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: wei25257758


  redis:
    database: 0
    host: 119.45.140.92
    port: 6379
    password:
    timeout: 6000ms


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lcfc.demo.modules.sys.entity

#  日志
logging:
  level:
    com.lcfc.demo.modules.sys.mapper: debug


